### ISSUE TITLE
BUG: All rides repaint immediately upon park load

### ISSUE THREAD

**Issue by ltsSmitty** [ltsSmitty/OpenRCT-Ride-Painter#3]
This isn't technically against the purpose of the feature, but it's not intended.

Could be solved by marking everything as having been painted upon parkInit(). not sure other potential issues with doing that though.

**Comment by ltsSmitty** [comment]
fixed with refactor of model code

**Comment by sudofox** [comment]
I'm still seeing this occurring with the latest release, with the Six Flags Great Adventure park colors. Great plugin but I don't want it repainting the classic rides

**Comment by ltsSmitty** [comment]
@sudofox Thanks for the note. I believe this has been fixed further after a substantial rebuild, but I haven't pushed the fix to release yet. I'm on a new pc and am having some data issues, but I'll ping on next release.

**Comment by 4vie** [comment]
Hey! Just wanted to pipe up and express interest in having the change uploaded when it convenient and possible, too!

**Comment by ltsSmitty** [comment]
Fixed along with other improvements in v1.2.0, live now. https://github.com/ltsSmitty/OpenRCT-Ride-Painter/releases/tag/v1.2.0

**Comment by ltsSmitty** [comment]
Thanks for your prompting! I'd love any feedback or ideas you have - you can find me on the OpenRCT discord at Smitty#5288!
